version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:  
  file:
    class: logging.FileHandler
    filename: 'UsingYamlConfig\loggingyaml.txt'
    formatter: simple    
    mode: 'w'
  console:  
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple    
loggers:
  example:
    level: INFO
    handlers: [console, file]
    propagate: False  
root:
  level: INFO
  handlers: [console, file]
